import { useState } from "react";
import { Sparkles, Download, Save, Copy, RefreshCw } from "lucide-react";

export function AIDocumentGenerator() {
  const [prompt, setPrompt] = useState("");
  const [generatedContent, setGeneratedContent] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const quickPrompts = [
    "Generate a comprehensive course syllabus for Data Structures and Algorithms",
    "Create a lesson plan for Introduction to Programming with learning outcomes",
    "Design a rubric for evaluating student research papers",
    "Draft a midterm examination for Database Management Systems",
    "Write learning module content for Object-Oriented Programming",
  ];

  const handleGenerate = () => {
    if (!prompt.trim()) return;

    setIsGenerating(true);
    setTimeout(() => {
      setGeneratedContent(`# AI-Generated Academic Document

## Document Overview
Based on your prompt: "${prompt}"

### Section 1: Introduction
This section provides a comprehensive overview of the topic, outlining the key concepts and objectives that will be covered throughout the document.

### Section 2: Learning Outcomes
Upon completion, students will be able to:
- Demonstrate understanding of core concepts
- Apply theoretical knowledge to practical scenarios
- Analyze and evaluate complex problems
- Create solutions using appropriate methodologies

### Section 3: Content Structure
The document follows a structured approach designed to facilitate progressive learning and ensure comprehensive coverage of the subject matter.

### Section 4: Assessment and Evaluation
Multiple assessment methods will be employed to evaluate student understanding and progress, including formative and summative assessments.

### Section 5: Resources and References
A curated list of academic resources, textbooks, and supplementary materials to support learning and further exploration.

---
*Generated by CTU Knowledge System AI Assistant*`);
      setIsGenerating(false);
    }, 3000);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedContent);
    alert("Content copied to clipboard!");
  };

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="h-8 w-8 text-[#FDB913]" />
            <h1 className="text-3xl text-gray-900">AI Document Generator</h1>
          </div>
          <p className="text-gray-600">Generate academic documents using AI-powered assistance</p>
        </div>
      </div>

      {/* AI Prompt Section */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-xl mb-4 text-[#CE0000]">Describe Your Document</h2>
        <div className="space-y-4">
          <div>
            <label className="block text-sm mb-2 text-gray-700">What would you like to generate?</label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={6}
              className="w-full px-4 py-3 bg-[#F5F5F5] border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#FDB913]"
              placeholder="Describe the document you want to generate. Be as specific as possible - include document type, subject area, target audience, key topics to cover, and any specific requirements..."
            />
          </div>

          <button
            onClick={handleGenerate}
            disabled={isGenerating || !prompt.trim()}
            className="w-full flex items-center justify-center gap-2 px-6 py-3 bg-[#CE0000] text-white rounded-lg hover:bg-[#b50000] transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isGenerating ? (
              <>
                <RefreshCw className="h-5 w-5 animate-spin" />
                Generating with AI...
              </>
            ) : (
              <>
                <Sparkles className="h-5 w-5" />
                Generate with AI
              </>
            )}
          </button>
        </div>
      </div>

      {/* Quick Prompts */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-xl mb-4 text-[#CE0000]">Quick Prompts</h2>
        <div className="space-y-2">
          {quickPrompts.map((quickPrompt, index) => (
            <button
              key={index}
              onClick={() => setPrompt(quickPrompt)}
              className="w-full text-left p-4 bg-[#F5F5F5] rounded-lg hover:bg-[#FDB913]/10 hover:border-[#FDB913] border-2 border-transparent transition-all"
            >
              <p className="text-gray-700 text-sm">{quickPrompt}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Generated Content */}
      {generatedContent && (
        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl text-[#CE0000]">Generated Content</h2>
            <div className="flex gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-2 px-4 py-2 text-[#006837] border border-[#006837] rounded-lg hover:bg-[#006837] hover:text-white transition-colors"
              >
                <Copy className="h-4 w-4" />
                Copy
              </button>
              <button className="flex items-center gap-2 px-4 py-2 bg-[#006837] text-white rounded-lg hover:bg-[#005329] transition-colors">
                <Save className="h-4 w-4" />
                Save
              </button>
              <button className="flex items-center gap-2 px-4 py-2 bg-[#FDB913] text-gray-900 rounded-lg hover:bg-[#e5a610] transition-colors">
                <Download className="h-4 w-4" />
                Export
              </button>
            </div>
          </div>

          <div className="p-6 bg-[#F5F5F5] rounded-lg border border-gray-300">
            <div className="prose max-w-none">
              <pre className="whitespace-pre-wrap text-gray-700 font-sans text-sm leading-relaxed">
                {generatedContent}
              </pre>
            </div>
          </div>

          <div className="mt-4 p-4 bg-[#FDB913]/10 border-l-4 border-[#FDB913] rounded">
            <p className="text-sm text-gray-700">
              <strong>Note:</strong> This is AI-generated content. Please review and edit as needed to ensure accuracy and alignment with your specific requirements.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
