"use client";

/**
 * AIDocumentGenerator.tsx
 * ---------------------------------------------------------------------------
 * Production-ready AI document generator for CTU (or any institution/brand).
 *
 * Generates ANY kind of document (academic, business, legal, invoices,
 * contracts, reports, proposals, letters, NDAs, certificates, etc.) from a
 * natural-language prompt, with optional user-supplied header/footer images
 * (letterhead) that are NEVER touched or generated by the AI. Exports to
 * DOCX (primary) and PDF (secondary).
 *
 * REQUIRED NPM PACKAGES
 * ---------------------------------------------------------------------------
 *   npm install docx file-saver jspdf lucide-react
 *   npm install -D @types/file-saver
 *
 * - docx        -> builds real .docx files (headers/footers/images/styles)
 * - file-saver  -> triggers the browser "Save As" download
 * - jspdf       -> builds the .pdf export (text-based, so it stays small,
 *                  selectable, and doesn't require rendering the DOM to a
 *                  canvas like the html2canvas approach would)
 * - lucide-react -> icons
 *
 * WHY jsPDF INSTEAD OF pdf-lib / html2canvas
 * ---------------------------------------------------------------------------
 * pdf-lib has no built-in text-wrapping/layout engine, and html2canvas
 * rasterizes the page (blurry text, huge file size, no selectable text).
 * jsPDF gives us simple, reliable text flow + image placement, which is all
 * a generated document needs, and keeps output crisp and searchable.
 *
 * CONNECTING A REAL AI API (Groq / OpenAI-compatible)
 * ---------------------------------------------------------------------------
 * 1. Create app/api/generate-document/route.ts (see the fully-commented
 *    example at the bottom of this file).
 * 2. Set your API key as a server-only env var, e.g. GROQ_API_KEY or
 *    OPENAI_API_KEY, in .env.local. Never expose it to the client.
 * 3. In this component, uncomment the `callRealAI` implementation inside
 *    `handleGenerate` and delete/comment out the mock generator.
 * 4. The API route should ONLY ever return body content. It must never be
 *    asked to design or generate a header/footer image or letterhead -
 *    that responsibility stays entirely client-side (see SYSTEM_PROMPT).
 */

import { useMemo, useRef, useState, type RefObject } from "react";
import {
  Sparkles,
  Copy,
  RefreshCw,
  Image as ImageIcon,
  X,
  FileText,
  FileDown,
  AlertCircle,
  CheckCircle2,
  ChevronDown,
  ChevronUp,
} from "lucide-react";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  ImageRun,
  AlignmentType,
  Header,
  Footer,
} from "docx";
import { saveAs } from "file-saver";
import jsPDF from "jspdf";

/* ============================================================================
 * BRAND TOKENS
 * ==========================================================================*/
const BRAND = {
  red: "#CE0000",
  redHover: "#b50000",
  yellow: "#FDB913",
  yellowHover: "#e5a610",
  green: "#006837",
  greenHover: "#005329",
  bg: "#F5F5F5",
};

/* ============================================================================
 * SYSTEM PROMPT (reference for the API route / real AI call)
 * ----------------------------------------------------------------------------
 * This is the instruction set the AI model should receive server-side. Keep
 * it in sync with app/api/generate-document/route.ts.
 * ==========================================================================*/
export const SYSTEM_PROMPT = `You are a professional document-drafting assistant embedded in an
institutional document generator.

RULES:
1. Generate ONLY the body content of the requested document (academic,
   business, legal, invoice, contract, report, proposal, letter, NDA,
   certificate, or any other document type the user describes).
2. NEVER generate, describe, or reference a header, footer, letterhead,
   logo, page-number block, or company seal. Those are controlled
   exclusively by the user's own image uploads outside of your output.
3. Do not wrap the response in markdown code fences.
4. Use clear structure, formatted like a formal printed document:
   - A single top-level title as the very first line, prefixed with "# ".
     Write it in Title Case (it will be centered and capitalized
     automatically) - keep it short, e.g. "# Property Management Agreement".
   - Section headings prefixed with "## ", short and in Title Case
     (e.g. "## Parties", "## Term", "## Responsibilities of the Agent").
     These render bold and underlined, matching standard legal/contract
     section headers - do not add numbering to them yourself.
   - For any information that must be filled in later by the user (names,
     dates, addresses, amounts, signatures), write a blank line using a
     run of underscores at least 15 characters long, e.g. "between
     ______________________ (the \"Owner\") and ______________________
     (the \"Agent\")". Do NOT use bracket placeholders like [Owner Name].
   - Use "- " for bulleted lists (e.g. responsibilities, clauses, line
     items). Use plain paragraphs for everything else. No HTML.
5. Match tone and formality to the document type requested (e.g. legal
   documents should read as formal legal prose with the blank-line
   convention above; invoices should use clean line-item structure;
   lesson plans should be structured and practical for an instructor).
6. Be complete and usable as a first draft - the user will review and
   edit before finalizing, but it should require minimal rewriting.`;

/* ============================================================================
 * QUICK PROMPTS
 * ==========================================================================*/
const QUICK_PROMPTS: string[] = [
  "Generate a comprehensive course syllabus for Data Structures and Algorithms",
  "Create a professional service invoice for a software development project",
  "Draft a formal employment contract for a full-time software engineer",
  "Write a project proposal for an AI-powered student portal",
  "Create a detailed lesson plan for Introduction to Programming",
  "Generate a business report analyzing Q2 performance",
  "Draft an NDA between two companies",
  "Write a cover letter for a teaching position",
  "Create a student research paper rubric",
  "Design a midterm examination for Database Management Systems",
];
const COLLAPSED_PROMPT_COUNT = 6;

/* ============================================================================
 * SHARED TYPES
 * ==========================================================================*/
type ImageAsset = {
  dataUrl: string; // base64 data URL, used for on-screen preview + PDF
  base64: string; // raw base64 (no prefix), used for docx ImageRun
  mimeType: "png" | "jpg" | "gif" | "bmp";
  width: number;
  height: number;
  fileName: string;
};

type GenerationStatus = "idle" | "generating" | "success" | "error";
type DownloadTarget = "docx" | "pdf" | null;

/* ============================================================================
 * IMAGE CONSTRAINTS
 * Keeps headers/footers looking professional and file sizes sane.
 * ==========================================================================*/
const MAX_IMAGE_DIMENSION_PX = 1600; // downscale ceiling
const MAX_IMAGE_SIZE_MB = 5;
const HEADER_FOOTER_DISPLAY_HEIGHT_PX = 70; // on-page target height in docx (px @96dpi)

const ACCEPTED_IMAGE_TYPES = ["image/png", "image/jpeg", "image/webp"];

/* ============================================================================
 * UTILITIES
 * ==========================================================================*/

/** Reads a File into a downsized base64 PNG/JPEG (via canvas), returning both
 *  a full data URL (for <img> previews) and the raw base64 payload (for
 *  docx's ImageRun, which wants bytes, not a data URL). */
async function fileToImageAsset(file: File): Promise<ImageAsset> {
  if (!ACCEPTED_IMAGE_TYPES.includes(file.type)) {
    throw new Error("Please upload a PNG, JPG, or WEBP image.");
  }
  if (file.size > MAX_IMAGE_SIZE_MB * 1024 * 1024) {
    throw new Error(`Image must be smaller than ${MAX_IMAGE_SIZE_MB}MB.`);
  }

  const rawDataUrl: string = await new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = () => reject(new Error("Could not read the image file."));
    reader.readAsDataURL(file);
  });

  const img = await new Promise<HTMLImageElement>((resolve, reject) => {
    const el = new window.Image();
    el.onload = () => resolve(el);
    el.onerror = () => reject(new Error("Could not decode the image file."));
    el.src = rawDataUrl;
  });

  // Downscale to keep the exported document a reasonable size.
  let { width, height } = img;
  if (width > MAX_IMAGE_DIMENSION_PX || height > MAX_IMAGE_DIMENSION_PX) {
    const scale = MAX_IMAGE_DIMENSION_PX / Math.max(width, height);
    width = Math.round(width * scale);
    height = Math.round(height * scale);
  }

  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas is not supported in this browser.");
  ctx.drawImage(img, 0, 0, width, height);

  // Always normalize to PNG so docx's ImageRun type stays predictable and
  // transparency (common in letterhead logos) is preserved.
  const dataUrl = canvas.toDataURL("image/png");
  const base64 = dataUrl.split(",")[1];

  return {
    dataUrl,
    base64,
    mimeType: "png",
    width,
    height,
    fileName: file.name,
  };
}

/** Converts a base64 PNG string into a Uint8Array for docx's ImageRun. */
function base64ToUint8Array(base64: string): Uint8Array {
  const binaryString = atob(base64);
  const bytes = new Uint8Array(binaryString.length);
  for (let i = 0; i < binaryString.length; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}

/** Very small markdown-ish parser: turns the AI's plain-text output into a
 *  list of typed blocks the DOCX/PDF builders can render consistently. */
type ContentBlock =
  | { type: "h1"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "bullet"; text: string }
  | { type: "paragraph"; text: string };

function parseContentToBlocks(raw: string): ContentBlock[] {
  const lines = raw.replace(/\r\n/g, "\n").split("\n");
  const blocks: ContentBlock[] = [];

  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line) continue;

    if (line.startsWith("### ")) {
      blocks.push({ type: "h3", text: line.slice(4).trim() });
    } else if (line.startsWith("## ")) {
      blocks.push({ type: "h2", text: line.slice(3).trim() });
    } else if (line.startsWith("# ")) {
      blocks.push({ type: "h1", text: line.slice(2).trim() });
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      blocks.push({ type: "bullet", text: line.slice(2).trim() });
    } else if (/^-{3,}$/.test(line)) {
      // horizontal rule markers from the mock generator - skip cleanly
      continue;
    } else {
      blocks.push({ type: "paragraph", text: line });
    }
  }
  return blocks;
}

function sanitizeFileNameSegment(input: string): string {
  return input
    .trim()
    .slice(0, 40)
    .replace(/[^a-z0-9\s-]/gi, "")
    .replace(/\s+/g, "_");
}

function buildFileBaseName(prompt: string): string {
  const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
  const slug = sanitizeFileNameSegment(prompt) || "Document";
  return `${slug}_${today}`;
}

/* ============================================================================
 * MOCK AI GENERATION (works immediately, no backend required)
 * Replace with `callRealAI` (see bottom of file) once the API route exists.
 * ==========================================================================*/
export async function mockGenerateDocument(prompt: string): Promise<string> {
  await new Promise((resolve) => setTimeout(resolve, 1800));

  const lower = prompt.toLowerCase();

  if (lower.includes("invoice")) {
    return `# Service Invoice

## Bill To
[Client Name]
[Client Company]
[Client Address]

## Invoice Details
Invoice #: INV-1001
Date: ${new Date().toLocaleDateString()}
Due Date: Net 30

## Line Items
- Software development services (80 hrs @ $95/hr) — $7,600.00
- UI/UX design consultation (10 hrs @ $85/hr) — $850.00
- Project management (15 hrs @ $75/hr) — $1,125.00

## Summary
Subtotal: $9,575.00
Tax (0%): $0.00
Total Due: $9,575.00

## Payment Terms
Payment is due within 30 days of the invoice date. Late payments may be subject to a 1.5% monthly finance charge.

## Notes
Thank you for your business. Please reach out with any questions regarding this invoice.`;
  }

  if (lower.includes("nda") || lower.includes("non-disclosure")) {
    return `# Mutual Non-Disclosure Agreement

## Parties
This Agreement is entered into between [Company A], and [Company B] (each a "Party" and together the "Parties").

## Purpose
The Parties wish to explore a potential business relationship and, in connection with that opportunity, may disclose certain confidential and proprietary information to each other.

## Confidential Information
"Confidential Information" means any non-public technical, business, or financial information disclosed by either Party, whether in written, oral, or electronic form, that is designated as confidential or that reasonably should be understood to be confidential.

## Obligations
- Each Party shall use the other's Confidential Information solely for evaluating the potential business relationship.
- Each Party shall protect the Confidential Information using at least the same degree of care it uses for its own confidential information, and no less than a reasonable standard of care.
- Confidential Information shall not be disclosed to any third party without prior written consent.

## Term
This Agreement shall remain in effect for two (2) years from the Effective Date, unless terminated earlier by mutual written consent.

## Governing Law
This Agreement shall be governed by the laws of [Jurisdiction], without regard to its conflict of law principles.

## Signatures
[Company A] — Authorized Signature, Date
[Company B] — Authorized Signature, Date`;
  }

  if (lower.includes("employment contract") || lower.includes("contract for a full-time")) {
    return `# Employment Agreement

## Position
This Employment Agreement is entered into between [Company Name] ("Employer") and [Employee Name] ("Employee") for the position of Software Engineer.

## Term and Type of Employment
Employee shall be employed on a full-time basis, commencing on [Start Date], subject to the terms set forth in this Agreement.

## Duties and Responsibilities
Employee shall perform the duties customarily associated with a Software Engineer role, including but not limited to designing, developing, testing, and maintaining software systems, and collaborating with cross-functional teams as reasonably directed by the Employer.

## Compensation
- Base Salary: $[Amount] per year, paid in accordance with the Employer's standard payroll schedule.
- Benefits: Employee shall be eligible for the Employer's standard benefits package, including health insurance and paid time off, subject to plan terms.

## Confidentiality
Employee agrees to maintain the confidentiality of the Employer's proprietary information both during and after the term of employment.

## Termination
Either Party may terminate this Agreement with [30] days' written notice, or immediately for cause as defined by Employer policy.

## Governing Law
This Agreement shall be governed by the laws of [Jurisdiction].

## Signatures
Employer — Authorized Signature, Date
Employee — Signature, Date`;
  }

  if (lower.includes("proposal")) {
    return `# Project Proposal: AI-Powered Student Portal

## Executive Summary
This proposal outlines the development of an AI-powered student portal designed to centralize academic records, personalize learning recommendations, and streamline communication between students, faculty, and administration.

## Problem Statement
Students currently rely on disconnected systems for grades, course materials, advising, and communication, leading to inefficiency and reduced engagement.

## Proposed Solution
- A unified dashboard consolidating grades, schedules, and announcements
- AI-driven course and resource recommendations based on academic history
- An integrated messaging system connecting students, instructors, and advisors
- Predictive alerts for at-risk students to support early intervention

## Scope and Deliverables
- Requirements gathering and system design
- Core portal development (frontend and backend)
- AI recommendation engine integration
- Pilot rollout with a defined student cohort
- Full-scale deployment and training

## Timeline
Estimated delivery: 4-6 months from project kickoff, delivered in phased milestones.

## Budget Overview
A detailed budget will be provided following requirements finalization, covering development, infrastructure, and support costs.

## Conclusion
This initiative will modernize the student experience, improve retention through early intervention, and reduce administrative overhead across departments.`;
  }

  if (lower.includes("cover letter")) {
    return `# Cover Letter

Dear Hiring Committee,

I am writing to express my interest in the teaching position at your institution. With a strong background in curriculum development and a genuine passion for student success, I am confident I would be a valuable addition to your faculty.

## Relevant Experience
Throughout my career, I have designed engaging course materials, mentored students through complex coursework, and collaborated with colleagues to continuously improve learning outcomes.

## Why I'm a Strong Fit
- Proven ability to translate complex material into accessible lessons
- Track record of high student engagement and positive evaluations
- Commitment to inclusive, student-centered teaching practices

## Closing
I would welcome the opportunity to discuss how my background and teaching philosophy align with your department's goals. Thank you for your time and consideration.

Sincerely,
[Your Name]`;
  }

  if (lower.includes("rubric")) {
    return `# Research Paper Evaluation Rubric

## Purpose
This rubric provides a consistent framework for evaluating student research papers across key academic dimensions.

## Criteria

### Thesis and Argument (25 points)
Clear, focused thesis statement supported by a coherent, well-developed argument throughout the paper.

### Research and Evidence (25 points)
Use of credible, relevant sources with appropriate citation and thoughtful synthesis of evidence.

### Organization and Structure (20 points)
Logical flow between sections, clear paragraph structure, and effective transitions.

### Writing Quality and Style (15 points)
Clarity, grammar, academic tone, and adherence to the required citation style.

### Originality and Critical Thinking (15 points)
Evidence of independent analysis, original insight, and critical engagement with source material beyond summary.

## Grading Scale
- 90-100: Excellent
- 80-89: Proficient
- 70-79: Developing
- Below 70: Needs Improvement`;
  }

  if (lower.includes("report") && lower.includes("performance")) {
    return `# Q2 Business Performance Report

## Executive Summary
This report analyzes business performance for the second quarter, highlighting key metrics, trends, and recommendations for the upcoming quarter.

## Financial Overview
- Revenue grew relative to Q1, driven primarily by increased customer retention
- Operating expenses remained within budget across all departments
- Gross margin improved due to operational efficiencies implemented in Q1

## Key Performance Indicators
- Customer acquisition cost decreased
- Customer satisfaction scores improved
- Employee retention remained stable

## Challenges
- Supply chain delays affected a subset of product deliveries
- Increased competition in the core market segment

## Recommendations
- Continue investment in customer retention initiatives
- Diversify supplier relationships to reduce delivery risk
- Expand marketing efforts in underperforming regions

## Conclusion
Overall, Q2 performance reflects steady, sustainable growth. Continued focus on operational efficiency and customer experience is recommended heading into Q3.`;
  }

  // Generic academic/document fallback
  return `# ${prompt.length > 60 ? prompt.slice(0, 60) + "..." : prompt}

## Overview
This document was generated based on your request: "${prompt}". It provides a structured starting point covering the essential sections for this type of document.

## Section 1: Introduction
This section introduces the purpose, scope, and objectives of the document.

## Section 2: Main Content
- Key point one, expanded with supporting detail
- Key point two, expanded with supporting detail
- Key point three, expanded with supporting detail

## Section 3: Details and Requirements
Additional detail relevant to the specific request should be developed here, tailored to the intended audience and purpose.

## Section 4: Conclusion
A brief closing section summarizing the document's key takeaways and any next steps.

Please review and edit this draft to ensure it precisely matches your requirements before finalizing.`;
}

/* ============================================================================
 * MAIN COMPONENT
 * ==========================================================================*/
export function DocumentGenerator() {
  const [prompt, setPrompt] = useState("");
  const [generatedContent, setGeneratedContent] = useState("");
  const [status, setStatus] = useState<GenerationStatus>("idle");
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [downloading, setDownloading] = useState<DownloadTarget>(null);
  const [copySuccess, setCopySuccess] = useState(false);
  const [showAllPrompts, setShowAllPrompts] = useState(false);

  // Header state
  const [headerImage, setHeaderImage] = useState<ImageAsset | null>(null);
  const [noHeader, setNoHeader] = useState(true);
  const [headerError, setHeaderError] = useState<string | null>(null);

  // Footer state
  const [footerImage, setFooterImage] = useState<ImageAsset | null>(null);
  const [noFooter, setNoFooter] = useState(true);
  const [footerError, setFooterError] = useState<string | null>(null);

  const headerInputRef = useRef<HTMLInputElement>(null);
  const footerInputRef = useRef<HTMLInputElement>(null);

  const visiblePrompts = useMemo(
    () => (showAllPrompts ? QUICK_PROMPTS : QUICK_PROMPTS.slice(0, COLLAPSED_PROMPT_COUNT)),
    [showAllPrompts]
  );

  /* ---------------------------------------------------------------------- */
  /* Image upload handlers                                                   */
  /* ---------------------------------------------------------------------- */
  const handleHeaderUpload = async (file: File | undefined) => {
    if (!file) return;
    setHeaderError(null);
    try {
      const asset = await fileToImageAsset(file);
      setHeaderImage(asset);
      setNoHeader(false);
    } catch (err) {
      setHeaderError(err instanceof Error ? err.message : "Could not process image.");
    } finally {
      if (headerInputRef.current) headerInputRef.current.value = "";
    }
  };

  const handleFooterUpload = async (file: File | undefined) => {
    if (!file) return;
    setFooterError(null);
    try {
      const asset = await fileToImageAsset(file);
      setFooterImage(asset);
      setNoFooter(false);
    } catch (err) {
      setFooterError(err instanceof Error ? err.message : "Could not process image.");
    } finally {
      if (footerInputRef.current) footerInputRef.current.value = "";
    }
  };

  const removeHeaderImage = () => {
    setHeaderImage(null);
    setHeaderError(null);
  };

  const removeFooterImage = () => {
    setFooterImage(null);
    setFooterError(null);
  };

  /* ---------------------------------------------------------------------- */
  /* Generation                                                               */
  /* ---------------------------------------------------------------------- */
  const handleGenerate = async () => {
    if (!prompt.trim()) return;

    setStatus("generating");
    setErrorMessage(null);

    try {
      // --- LIVE AI CALL via /api/generate-document (OpenAI) ----------------
      const content = await callRealAI(prompt);

      // --- MOCK (no backend required) — switch back to this for offline dev:
      // const content = await mockGenerateDocument(prompt);

      setGeneratedContent(content);
      setStatus("success");
    } catch (err) {
      setErrorMessage(
        err instanceof Error ? err.message : "Something went wrong while generating your document."
      );
      setStatus("error");
    }
  };

  /** Calls our own Next.js API route, which in turn calls OpenAI server-side.
   *  Keeping the API key out of the browser is why this two-hop setup exists:
   *  the component never talks to OpenAI directly. */
  async function callRealAI(userPrompt: string): Promise<string> {
    const response = await fetch("/api/generate-document", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ prompt: userPrompt }),
    });
    if (!response.ok) {
      const body = await response.json().catch(() => null);
      throw new Error(body?.error ?? "The AI service could not generate this document.");
    }
    const data = await response.json();
    return data.content as string;
  }

  /* ---------------------------------------------------------------------- */
  /* Copy                                                                     */
  /* ---------------------------------------------------------------------- */
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(generatedContent);
      setCopySuccess(true);
      setTimeout(() => setCopySuccess(false), 2000);
    } catch {
      setErrorMessage("Could not copy to clipboard. Please copy the text manually.");
    }
  };

  /* ---------------------------------------------------------------------- */
  /* DOCX export                                                              */
  /* ---------------------------------------------------------------------- */
  const handleDownloadDocx = async () => {
    if (!generatedContent.trim()) return;
    setDownloading("docx");
    setErrorMessage(null);

    try {
      const blocks = parseContentToBlocks(generatedContent);

      const bodyParagraphs = blocks.map((block) => {
        switch (block.type) {
          case "h1":
            return new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { before: 120, after: 280 },
              children: [
                new TextRun({
                  text: block.text.toUpperCase(),
                  bold: true,
                  size: 32, // 16pt
                }),
              ],
            });
          case "h2":
            return new Paragraph({
              spacing: { before: 260, after: 140 },
              children: [
                new TextRun({
                  text: block.text,
                  bold: true,
                  underline: {},
                  size: 24, // 12pt
                }),
              ],
            });
          case "h3":
            return new Paragraph({
              spacing: { before: 200, after: 110 },
              children: [
                new TextRun({
                  text: block.text,
                  bold: true,
                  underline: {},
                  size: 22, // 11pt
                }),
              ],
            });
          case "bullet":
            return new Paragraph({
              text: block.text,
              bullet: { level: 0 },
              spacing: { after: 80 },
            });
          case "paragraph":
          default:
            return new Paragraph({
              children: [new TextRun(block.text)],
              spacing: { after: 120 },
              alignment: AlignmentType.LEFT,
            });
        }
      });

      // Header: user-uploaded image only, centered. AI never writes this.
      const headerContent =
        !noHeader && headerImage
          ? new Header({
              children: [
                new Paragraph({
                  alignment: AlignmentType.CENTER,
                  children: [
                    new ImageRun({
                      data: base64ToUint8Array(headerImage.base64),
                      transformation: scaledDocxDimensions(headerImage),
                      type: "png",
                    }),
                  ],
                }),
              ],
            })
          : new Header({ children: [new Paragraph("")] });

      // Footer: same rule - user image only, or blank.
      const footerContent =
        !noFooter && footerImage
          ? new Footer({
              children: [
                new Paragraph({
                  alignment: AlignmentType.CENTER,
                  children: [
                    new ImageRun({
                      data: base64ToUint8Array(footerImage.base64),
                      transformation: scaledDocxDimensions(footerImage),
                      type: "png",
                    }),
                  ],
                }),
              ],
            })
          : new Footer({ children: [new Paragraph("")] });

      const doc = new Document({
        sections: [
          {
            properties: {
              page: {
                margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
              },
            },
            headers: { default: headerContent },
            footers: { default: footerContent },
            children: bodyParagraphs,
          },
        ],
        styles: {
          default: {
            document: {
              run: { font: "Calibri", size: 22 }, // 11pt
            },
          },
        },
      });

      const blob = await Packer.toBlob(doc);
      saveAs(blob, `${buildFileBaseName(prompt)}.docx`);
    } catch (err) {
      setErrorMessage(
        err instanceof Error ? err.message : "Could not generate the DOCX file. Please try again."
      );
    } finally {
      setDownloading(null);
    }
  };

  /* ---------------------------------------------------------------------- */
  /* PDF export                                                               */
  /* ---------------------------------------------------------------------- */
  const handleDownloadPdf = async () => {
    if (!generatedContent.trim()) return;
    setDownloading("pdf");
    setErrorMessage(null);

    try {
      const doc = new jsPDF({ unit: "pt", format: "letter" }); // 612 x 792 pt
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const marginX = 56; // ~0.78in
      const contentWidth = pageWidth - marginX * 2;

      const headerReservedHeight = !noHeader && headerImage ? 70 : 0;
      const footerReservedHeight = !noFooter && footerImage ? 60 : 0;
      const topMargin = 50 + headerReservedHeight;
      const bottomMargin = 50 + footerReservedHeight;

      let cursorY = topMargin;

      const drawHeaderFooterOnPage = () => {
        if (!noHeader && headerImage) {
          const { width, height } = fitDimensions(headerImage, contentWidth, 60);
          const x = marginX + (contentWidth - width) / 2;
          doc.addImage(headerImage.dataUrl, "PNG", x, 24, width, height);
        }
        if (!noFooter && footerImage) {
          const { width, height } = fitDimensions(footerImage, contentWidth, 50);
          const x = marginX + (contentWidth - width) / 2;
          doc.addImage(footerImage.dataUrl, "PNG", x, pageHeight - bottomMargin + 10, width, height);
        }
      };

      const ensureSpace = (neededHeight: number) => {
        if (cursorY + neededHeight > pageHeight - bottomMargin) {
          drawHeaderFooterOnPage();
          doc.addPage();
          cursorY = topMargin;
        }
      };

      const blocks = parseContentToBlocks(generatedContent);

      for (const block of blocks) {
        let fontSize = 11;
        let fontStyle: "normal" | "bold" = "normal";
        let prefix = "";
        let extraSpacingBefore = 6;
        let lineHeight = 15;

        if (block.type === "h1") {
          fontSize = 18;
          fontStyle = "bold";
          extraSpacingBefore = 18;
          lineHeight = 22;
        } else if (block.type === "h2") {
          fontSize = 14;
          fontStyle = "bold";
          extraSpacingBefore = 14;
          lineHeight = 18;
        } else if (block.type === "h3") {
          fontSize = 12.5;
          fontStyle = "bold";
          extraSpacingBefore = 10;
          lineHeight = 16;
        } else if (block.type === "bullet") {
          prefix = "•  ";
        }

        doc.setFont("helvetica", fontStyle);
        doc.setFontSize(fontSize);

        const displayText = block.type === "h1" ? block.text.toUpperCase() : block.text;
        const text = prefix + displayText;
        const wrapWidth = block.type === "bullet" ? contentWidth - 14 : contentWidth;
        const lines: string[] = doc.splitTextToSize(text, wrapWidth);

        cursorY += extraSpacingBefore;
        ensureSpace(lines.length * lineHeight);

        const isUnderlinedHeading = block.type === "h2" || block.type === "h3";

        for (const line of lines) {
          ensureSpace(lineHeight);

          let xPos = marginX;
          if (block.type === "h1") {
            const lineWidth = doc.getTextWidth(line);
            xPos = marginX + (contentWidth - lineWidth) / 2;
          } else if (block.type === "bullet" && line !== lines[0]) {
            xPos = marginX + 14;
          }

          doc.text(line, xPos, cursorY);

          if (isUnderlinedHeading) {
            const lineWidth = doc.getTextWidth(line);
            doc.setLineWidth(0.75);
            doc.line(xPos, cursorY + 2, xPos + lineWidth, cursorY + 2);
          }

          cursorY += lineHeight;
        }
      }

      // Draw header/footer on the final page too.
      drawHeaderFooterOnPage();

      // Backfill header/footer on every earlier page (addImage above only
      // draws on the page active at that time, so re-walk all pages once).
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        if (!noHeader && headerImage) {
          const { width, height } = fitDimensions(headerImage, contentWidth, 60);
          const x = marginX + (contentWidth - width) / 2;
          doc.addImage(headerImage.dataUrl, "PNG", x, 24, width, height);
        }
        if (!noFooter && footerImage) {
          const { width, height } = fitDimensions(footerImage, contentWidth, 50);
          const x = marginX + (contentWidth - width) / 2;
          doc.addImage(footerImage.dataUrl, "PNG", x, pageHeight - bottomMargin + 10, width, height);
        }
      }

      doc.save(`${buildFileBaseName(prompt)}.pdf`);
    } catch (err) {
      setErrorMessage(
        err instanceof Error ? err.message : "Could not generate the PDF file. Please try again."
      );
    } finally {
      setDownloading(null);
    }
  };

  /* ---------------------------------------------------------------------- */
  /* Render                                                                   */
  /* ---------------------------------------------------------------------- */
  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="h-8 w-8" style={{ color: BRAND.yellow }} />
            <h1 className="text-3xl text-gray-900">AI Document Generator</h1>
          </div>
          <p className="text-gray-600">
            Generate any document — academic, business, or legal — using AI-powered assistance.
          </p>
        </div>
      </div>

      {/* Global error banner */}
      {errorMessage && (
        <div className="flex items-start gap-3 p-4 bg-red-50 border-l-4 rounded" style={{ borderColor: BRAND.red }}>
          <AlertCircle className="h-5 w-5 mt-0.5 flex-shrink-0" style={{ color: BRAND.red }} />
          <p className="text-sm text-gray-700">{errorMessage}</p>
        </div>
      )}

      {/* Prompt Section */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-xl mb-4" style={{ color: BRAND.red }}>
          Describe Your Document
        </h2>
        <div className="space-y-4">
          <div>
            <label className="block text-sm mb-2 text-gray-700">What would you like to generate?</label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              rows={6}
              className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 transition-shadow"
              style={{ backgroundColor: BRAND.bg, ["--tw-ring-color" as string]: BRAND.yellow }}
              placeholder="Describe the document you want to generate. Be as specific as possible — document type, subject/purpose, audience, key sections, and any specific requirements..."
            />
          </div>

          {/* Header upload */}
          <ImageUploadField
            label="Header Image (Letterhead)"
            helperText="Shown centered at the top of every page. The AI never writes header content — only your uploaded image appears here."
            noneLabel="No Header"
            noneChecked={noHeader}
            onNoneChange={(checked) => {
              setNoHeader(checked);
              if (checked) removeHeaderImage();
            }}
            image={headerImage}
            error={headerError}
            inputRef={headerInputRef}
            onFileSelected={handleHeaderUpload}
            onRemove={removeHeaderImage}
          />

          {/* Footer upload */}
          <ImageUploadField
            label="Footer Image"
            helperText="Shown centered at the bottom of every page. The AI never writes footer content — only your uploaded image appears here."
            noneLabel="No Footer"
            noneChecked={noFooter}
            onNoneChange={(checked) => {
              setNoFooter(checked);
              if (checked) removeFooterImage();
            }}
            image={footerImage}
            error={footerError}
            inputRef={footerInputRef}
            onFileSelected={handleFooterUpload}
            onRemove={removeFooterImage}
          />

          <button
            onClick={handleGenerate}
            disabled={status === "generating" || !prompt.trim()}
            className="w-full flex items-center justify-center gap-2 px-6 py-3 text-white rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            style={{ backgroundColor: BRAND.red }}
            onMouseEnter={(e) => {
              if (status !== "generating") (e.currentTarget as HTMLButtonElement).style.backgroundColor = BRAND.redHover;
            }}
            onMouseLeave={(e) => {
              (e.currentTarget as HTMLButtonElement).style.backgroundColor = BRAND.red;
            }}
          >
            {status === "generating" ? (
              <>
                <RefreshCw className="h-5 w-5 animate-spin" />
                Generating with AI...
              </>
            ) : (
              <>
                <Sparkles className="h-5 w-5" />
                Generate with AI
              </>
            )}
          </button>
        </div>
      </div>

      {/* Quick Prompts */}
      <div className="bg-white rounded-lg shadow-md p-6">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-xl" style={{ color: BRAND.red }}>
            Quick Prompts
          </h2>
          <button
            onClick={() => setShowAllPrompts((v) => !v)}
            className="flex items-center gap-1 text-sm text-gray-600 hover:text-gray-900 transition-colors"
          >
            {showAllPrompts ? (
              <>
                Show less <ChevronUp className="h-4 w-4" />
              </>
            ) : (
              <>
                Show all ({QUICK_PROMPTS.length}) <ChevronDown className="h-4 w-4" />
              </>
            )}
          </button>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
          {visiblePrompts.map((quickPrompt, index) => (
            <button
              key={index}
              onClick={() => setPrompt(quickPrompt)}
              className="w-full text-left p-4 rounded-lg border-2 border-transparent transition-all hover:border-current"
              style={{ backgroundColor: BRAND.bg }}
              onMouseEnter={(e) => {
                (e.currentTarget as HTMLButtonElement).style.backgroundColor = `${BRAND.yellow}1A`;
                (e.currentTarget as HTMLButtonElement).style.borderColor = BRAND.yellow;
              }}
              onMouseLeave={(e) => {
                (e.currentTarget as HTMLButtonElement).style.backgroundColor = BRAND.bg;
                (e.currentTarget as HTMLButtonElement).style.borderColor = "transparent";
              }}
            >
              <p className="text-gray-700 text-sm">{quickPrompt}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Generated Content */}
      {status !== "idle" && (status === "generating" || generatedContent) && (
        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
            <h2 className="text-xl" style={{ color: BRAND.red }}>
              Generated Content
            </h2>

            {generatedContent && status !== "generating" && (
              <div className="flex gap-2 flex-wrap">
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-2 px-4 py-2 rounded-lg border transition-colors"
                  style={{ color: BRAND.green, borderColor: BRAND.green }}
                >
                  {copySuccess ? <CheckCircle2 className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                  {copySuccess ? "Copied!" : "Copy"}
                </button>
                <button
                  onClick={handleDownloadDocx}
                  disabled={downloading !== null}
                  className="flex items-center gap-2 px-4 py-2 text-white rounded-lg transition-colors disabled:opacity-50"
                  style={{ backgroundColor: BRAND.green }}
                >
                  {downloading === "docx" ? (
                    <RefreshCw className="h-4 w-4 animate-spin" />
                  ) : (
                    <FileText className="h-4 w-4" />
                  )}
                  Download DOCX
                </button>
                <button
                  onClick={handleDownloadPdf}
                  disabled={downloading !== null}
                  className="flex items-center gap-2 px-4 py-2 text-gray-900 rounded-lg transition-colors disabled:opacity-50"
                  style={{ backgroundColor: BRAND.yellow }}
                >
                  {downloading === "pdf" ? (
                    <RefreshCw className="h-4 w-4 animate-spin" />
                  ) : (
                    <FileDown className="h-4 w-4" />
                  )}
                  Download PDF
                </button>
              </div>
            )}
          </div>

          {status === "generating" ? (
            <div className="p-10 flex flex-col items-center justify-center gap-3 rounded-lg border border-gray-300" style={{ backgroundColor: BRAND.bg }}>
              <RefreshCw className="h-8 w-8 animate-spin" style={{ color: BRAND.red }} />
              <p className="text-sm text-gray-600">Drafting your document...</p>
            </div>
          ) : (
            <>
              <label className="block text-sm mb-2 text-gray-700">
                Edit the content below before downloading
              </label>
              <textarea
                value={generatedContent}
                onChange={(e) => setGeneratedContent(e.target.value)}
                rows={18}
                className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 font-mono text-sm leading-relaxed text-gray-700"
                style={{ backgroundColor: BRAND.bg, ["--tw-ring-color" as string]: BRAND.yellow }}
              />

              <div
                className="mt-4 p-4 border-l-4 rounded"
                style={{ backgroundColor: `${BRAND.yellow}1A`, borderColor: BRAND.yellow }}
              >
                <p className="text-sm text-gray-700">
                  <strong>Note:</strong> This is AI-generated content. Please review and edit as needed
                  before exporting. Header and footer images (if provided) are inserted exactly as
                  uploaded and are never modified by the AI.
                </p>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
}

/* ============================================================================
 * SUBCOMPONENT: Header / Footer image upload field
 * ==========================================================================*/
function ImageUploadField(props: {
  label: string;
  helperText: string;
  noneLabel: string;
  noneChecked: boolean;
  onNoneChange: (checked: boolean) => void;
  image: ImageAsset | null;
  error: string | null;
  inputRef: RefObject<HTMLInputElement | null>;
  onFileSelected: (file: File | undefined) => void;
  onRemove: () => void;
}) {
  const {
    label,
    helperText,
    noneLabel,
    noneChecked,
    onNoneChange,
    image,
    error,
    inputRef,
    onFileSelected,
    onRemove,
  } = props;

  return (
    <div className="border border-gray-200 rounded-lg p-4" style={{ backgroundColor: "#FAFAFA" }}>
      <div className="flex items-center justify-between flex-wrap gap-2 mb-2">
        <span className="text-sm text-gray-700 font-medium">{label}</span>
        <label className="flex items-center gap-2 text-sm text-gray-600 cursor-pointer select-none">
          <input
            type="checkbox"
            checked={noneChecked}
            onChange={(e) => onNoneChange(e.target.checked)}
            className="h-4 w-4 rounded border-gray-300"
            style={{ accentColor: BRAND.red }}
          />
          {noneLabel}
        </label>
      </div>
      <p className="text-xs text-gray-500 mb-3">{helperText}</p>

      {error && <p className="text-xs mb-2" style={{ color: BRAND.red }}>{error}</p>}

      {!noneChecked && (
        <>
          {!image ? (
            <button
              type="button"
              onClick={() => inputRef.current?.click()}
              className="w-full flex flex-col items-center justify-center gap-2 py-6 border-2 border-dashed rounded-lg text-gray-500 hover:text-gray-700 transition-colors"
              style={{ borderColor: "#D1D5DB" }}
            >
              <ImageIcon className="h-6 w-6" />
              <span className="text-sm">Click to upload PNG, JPG, or WEBP</span>
            </button>
          ) : (
            <div className="relative inline-block">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={image.dataUrl}
                alt={`${label} preview`}
                className="max-h-24 rounded border border-gray-300 bg-white p-1"
              />
              <button
                type="button"
                onClick={onRemove}
                aria-label={`Remove ${label.toLowerCase()}`}
                className="absolute -top-2 -right-2 h-6 w-6 flex items-center justify-center rounded-full text-white shadow"
                style={{ backgroundColor: BRAND.red }}
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          )}
          <input
            ref={inputRef}
            type="file"
            accept={ACCEPTED_IMAGE_TYPES.join(",")}
            className="hidden"
            onChange={(e) => onFileSelected(e.target.files?.[0])}
          />
        </>
      )}
    </div>
  );
}

/* ============================================================================
 * DOCX image scaling helper
 * Keeps the aspect ratio and caps the on-page height so header/footer images
 * never dominate the page.
 * ==========================================================================*/
function scaledDocxDimensions(image: ImageAsset): { width: number; height: number } {
  const maxHeight = HEADER_FOOTER_DISPLAY_HEIGHT_PX;
  const aspect = image.width / image.height;
  const height = Math.min(maxHeight, image.height);
  const width = Math.round(height * aspect);
  return { width, height: Math.round(height) };
}

/** Fits an image within a max width/height box for the PDF renderer,
 *  preserving aspect ratio. */
function fitDimensions(
  image: ImageAsset,
  maxWidth: number,
  maxHeight: number
): { width: number; height: number } {
  const aspect = image.width / image.height;
  let width = maxWidth;
  let height = width / aspect;
  if (height > maxHeight) {
    height = maxHeight;
    width = height * aspect;
  }
  return { width, height };
}

/* ============================================================================
 * EXAMPLE NEXT.JS API ROUTE (reference only — create as a separate file)
 * app/api/generate-document/route.ts
 * ----------------------------------------------------------------------------
 *
 * import { NextRequest, NextResponse } from "next/server";
 *
 * const SYSTEM_PROMPT = `...same SYSTEM_PROMPT exported above...`;
 *
 * export async function POST(req: NextRequest) {
 *   try {
 *     const { prompt } = await req.json();
 *     if (!prompt || typeof prompt !== "string") {
 *       return NextResponse.json({ error: "A prompt is required." }, { status: 400 });
 *     }
 *
 *     // Example using an OpenAI-compatible endpoint (works for Groq too by
 *     // swapping the baseURL and model, e.g. "https://api.groq.com/openai/v1"
 *     // and "llama-3.3-70b-versatile").
 *     const response = await fetch("https://api.openai.com/v1/chat/completions", {
 *       method: "POST",
 *       headers: {
 *         "Content-Type": "application/json",
 *         Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
 *       },
 *       body: JSON.stringify({
 *         model: "gpt-4o-mini",
 *         messages: [
 *           { role: "system", content: SYSTEM_PROMPT },
 *           { role: "user", content: prompt },
 *         ],
 *         temperature: 0.7,
 *       }),
 *     });
 *
 *     if (!response.ok) {
 *       return NextResponse.json(
 *         { error: "The AI service could not generate this document." },
 *         { status: 502 }
 *       );
 *     }
 *
 *     const data = await response.json();
 *     const content: string = data.choices?.[0]?.message?.content ?? "";
 *
 *     return NextResponse.json({ content });
 *   } catch (err) {
 *     return NextResponse.json({ error: "Unexpected server error." }, { status: 500 });
 *   }
 * }
 * ==========================================================================*/